language: node_js
node_js:
  - 12
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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
  local_dir: out
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|main)$
env: 
  CI: false
